<!DOCTYPE html>
<html lang='en' dir='ltr' class='sid-plesk'>
   <head>
      <title>MMRadio</title>
      <meta name='copyright' content='Copyright 1999-2016. Parallels IP Holdings GmbH. All Rights Reserved.'>
      <meta charset='utf-8'>
      <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
      <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0'>
      <meta http-equiv='Cache-Control' content='no-cache'>
      <link rel='shortcut icon' href='favicon.ico'>
      <link rel='stylesheet' href='css/bootstrap.min.css'>
      <link rel='stylesheet' href='css/reboot.min.css'>
      <link rel='stylesheet' href='css/bootstrap-grid.min.css'>
      <link rel='stylesheet' href='css/style.css'>
   </head>
   <body>
      <div class='page-container'>
         <!-- start: PAGE HEADER-->
         <div class='page-header-wrapper'>
            <div class='page-header'>
               <a class='product-logo' href='http://www.plesk.com/' target='_blank'><img src='img/logo.png' alt='Plesk'></a>
            </div>
         </div>
         <!-- end: PAGE HEADER-->

         <!-- start: PAGE CONTENT-->
         <div class='page-content-wrapper'>
            <div class='page-content'>
               <div class='product-info-wrapper'>
                  <div class='col'>
                     <div class='product-info'>
                        <div class='product-info-heading'>What is Plesk</div>
                        <div class='product-info-content'>
                           <p><strong><a href='http://www.plesk.com' target='_blank'>Plesk</a></strong> is a hosting control panel with simple and secure web server and website management tools. It was specially designed to help IT specialists manage web, DNS, mail and other services through a comprehensive and user-friendly GUI. <a class='more' href='http://www.plesk.com' target='_blank'>Learn more about Plesk</a>.</p>
                           <ul class='links'>
                              <li><a class='blog' href='http://devblog.plesk.com/' target='_blank'><span>Developer Blog</span></a></li>
                              <li><a class='forum' href='http://talk.plesk.com/' target='_blank'><span>Forum</span></a></li>
                              <li><a class='knowledge-base' href='http://kb.plesk.com/' target='_blank'><span>Knowledge Base</span></a></li>
                              <li><a class='facebook' href='https://www.facebook.com/Plesk' target='_blank'><span>Facebook</span></a></li>
                              <li><a class='twitter' href='https://twitter.com/PleskOfficial' target='_blank'><span>Twitter</span></a></li>
                              <li><a class='google-plus' href='https://plus.google.com/communities/109881979300958500728' target='_blank'><span>Google+</span></a></li>
                              <li><a class='google-plus' href='https://plus.google.com/communities/109881979300958500728' target='_blank'><span>TEST+</span></a></li>
                           </ul>
                        </div>
                     </div>
                  </div>
                  <div class='col'>
                     <div class='product-info'>
                        <div class='product-info-heading'>Test pages</div>
                        <div class='product-info-content'>
                           <p>Plesk provides several test pages that you can use for checking the scripting features, testing database connections and mail sending.</p>
                           <p>Click an icon to see test pages for different scripts:</p>
                           <ul class='links'>
                              <li><a class='fastcgi' href='test/fcgi/test.html'><span>FastCGI</span></a></li>
                              <li><a class='python' href='test/python/test.html'><span>Python</span></a></li>
                              <li><a class='php' href='test/php/test.html'><span>PHP</span></a></li>
                              <li><a class='perl' href='test/perl/test.html'><span>Perl</span></a></li>
                              <li><a class='ssi' href='test/ssi/test.html'><span>SSI</span></a></li>
                           </ul>
                        </div>
                     </div>
                  </div>
               </div> <!-- /.product-info-wrapper -->

            </div>
         </div>
         <!-- end: PAGE CONTENT-->

         <!-- start: PAGE FOOTER-->
         <div class='page-footer-wrapper'>
            <div class='page-footer'>
               This page was generated by Plesk. Plesk is the leading WebOps platform to run, automate and grow applications, websites and hosting businesses. Learn more at <a href='http://www.plesk.com' target='_blank'>plesk.com</a>.
            </div>
         </div>
         <!-- end: PAGE FOOTER-->
      </div>
      <script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'></script>
      <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js' integrity='sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh' crossorigin='anonymous'></script>
      <script src='js/bootstrap.min.js'></script>
      <script src='js/bootstrap-bundle.min.js'></script>
   </body>
</html>
